/**
 * Stable API error codes — keep in sync with apartmentscloneserver/utils/api_errors.go
 */
export const ApiErrorCode = {
  // Server
  SERVER_OK: "SERVER_OK",
  SERVER_INTERNAL: "SERVER_INTERNAL",
  SERVER_UNAVAILABLE: "SERVER_UNAVAILABLE",

  // Client-only (network layer)
  NET_NO_RESPONSE: "NET_NO_RESPONSE",
  NET_TIMEOUT: "NET_TIMEOUT",
  NET_DNS: "NET_DNS",
  NET_OFFLINE: "NET_OFFLINE",
  NET_SSL: "NET_SSL",
  NET_UNKNOWN: "NET_UNKNOWN",

  // Auth
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_PHONE_EXISTS: "AUTH_PHONE_EXISTS",
  AUTH_PHONE_INVALID: "AUTH_PHONE_INVALID",
  AUTH_SOCIAL_LOGIN: "AUTH_SOCIAL_LOGIN",
  AUTH_REGISTRATION_FAILED: "AUTH_REGISTRATION_FAILED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_NO_TOKEN: "AUTH_NO_TOKEN",

  // User check (/user/check-exists)
  USER_CHECK_INVALID_BODY: "USER_CHECK_INVALID_BODY",
  USER_CHECK_NO_IDENTIFIER: "USER_CHECK_NO_IDENTIFIER",
  USER_CHECK_BOTH_IDENTIFIERS: "USER_CHECK_BOTH_IDENTIFIERS",
  USER_CHECK_FAILED: "USER_CHECK_FAILED",

  // Generic
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  DATABASE_ERROR: "DATABASE_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;

export type ApiErrorCodeType =
  (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
