import { Apartment } from "./apartment";
import { Review } from "./review";
import { Pet } from "./pet";
import { Score } from "./score";
import { TempApartment } from "./tempApartment";

export type Host = {
  ID: number;
  firstName: string;
  lastName: string;
  avatarURL?: string;
  bio?: string;
  languages?: string[];
  isVerified?: boolean;
  verificationStatus?: string;
  rating?: number;
  responseTime?: string;
  joinedDate?: string;
};

export type Property = {
  ID: number;
  images: string[];
  title: string;
  description?: string;
  propertyType: "entire_place" | "private_room" | "shared_room" | string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  lat: number;
  lng: number;
  capacity: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  nightlyPrice: number;
  cleaningFee?: number;
  serviceFee?: number;
  currency: string;
  amenities?: string[];
  houseRules?: string;
  cancellationPolicy?: string;
  rating?: number;
  reviews?: Review[];
  liked?: boolean;
  host?: Host;
  isActive?: boolean;
  bookingMode?: string;
  secureCompoundAcknowledged?: boolean;
  equipmentViolationPolicyAccepted?: boolean;
  userSafetyPolicyAccepted?: boolean;
  propertyPolicyAccepted?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type CreateProperty = CreateListing;

export type CreateListing = {
  hostID: number;
  title: string;
  description?: string;
  propertyType: "entire_place" | "private_room" | "shared_room" | string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  lat: number;
  lng: number;
  capacity: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  nightlyPrice: number;
  cleaningFee?: number;
  serviceFee?: number;
  currency: string;
  amenities?: string[];
  houseRules?: string;
  cancellationPolicy?: string;
  images?: string[];
  isActive?: boolean;
  bookingMode?: string;
  secureCompoundAcknowledged?: boolean;
  equipmentViolationPolicyAccepted?: boolean;
  userSafetyPolicyAccepted?: boolean;
  propertyPolicyAccepted?: boolean;
  // Neighborhood and timing fields
  neighborhoodDescription?: string;
  nearbyAttractions?: Array<{name: string, distance: string}>;
  checkInTime?: string;
  checkOutTime?: string;
};

export type EditPropertyObj = {
  ID?: number;
  unitType?: "single" | "multiple";
  apartments: TempApartment[];
  description: string;
  images: string[];
  includedUtilities: string[];
  petsAllowed: string;
  laundryType: string;
  parkingFee: number;
  amenities: string[];
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  callingCode?: string;
  countryCode?: string;
  phoneNumber: string;
  website: string;
  onMarket: boolean;
};
