import React from 'react';
import {
  // Basic shapes and symbols
  Square,
  Triangle,
  Diamond,
  Hexagon,
  Pentagon,
  Octagon,
  Plus,
  Minus,
  Equals,
  X,
  Check,
  Warning,
  Info,
  Question,
  ExclamationMarkIcon,
  
  // Navigation and location
  MapPin,
  Compass,
  Globe,
  Flag,
  
  // Buildings and structures
  House,
  Building,
  HouseLine,
  Key,
  Lock,
  
  // Rooms and furniture
  Bed,
  Bathtub,
  Toilet,
  Shower,
  Dress,
  Backpack,
  Suitcase,
  
  // Technology
  WifiHigh,
  Phone,
  Printer,
  HardDrive,
  Camera,
  Video,
  VideoCamera,
  VideoCameraSlash,
  Webcam,
  WebcamSlash,
  Monitor,
  MonitorPlay,
  Television,
  
  // Appliances and utilities
  Lightbulb,
  Flashlight,
  Lamp,
  Plug,
  WashingMachine,
  Fan,
  Thermometer,
  ThermometerHot,
  ThermometerCold,
  
  // Transportation
  Car,
  Airplane,
  
  // Nature and weather
  Tree,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Fire,
  Snowflake,
  
  // Water and swimming
  Waves,
  SwimmingPool,
  Drop,
  
  // Sports and fitness
  Barbell,
  
  // Entertainment
  GameController,
  MusicNote,
  
  // Animals and pets
  PawPrint,
  
  // People and accessibility
  Baby,
  Wheelchair,
  Users,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  
  // Security and safety
  Shield,
  
  // Food and drink
  Coffee,
  
  // Time and calendar
  Clock,
  Calendar,
  
  // Communication
  Bell,
  BellSlash,
  Microphone,
  MicrophoneSlash,
  Chat,
  ChatCircle,
  ChatDots,
  ChatText,
  ChatTeardrop,
  ChatTeardropDots,
  ChatTeardropText,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneSlash,
  PhoneX,
  Envelope,
  EnvelopeOpen,
  Mailbox,
  PaperPlane,
  
  // Files and documents
  File,
  Folder,
  Download,
  Upload,
  Share,
  Copy,
  Scissors,
  Trash,
  Archive,
  Bookmark,
  BookmarkSimple,
  Tag,
  Hash,
  At,
  Link,
  LinkBreak,
  Paperclip,
  
  // Presentation and charts
  Presentation,
  PresentationChart,
  TrendUp,
  TrendDown,
  
  // Health and medical
  Pulse,
  Heartbeat,
  
  // Science and education
  Planet,
  Rocket,
  Binoculars,
  Microscope,
  Flask,
  Atom,
  TestTube,
  GraduationCap,
  Book,
  BookOpen,
  Books,
  Calculator,
  Ruler,
  
  // Miscellaneous
  Star,
  Heart,
  ThumbsUp,
  Eye,
  EyeSlash,
  Image,
  Elevator,
  BatteryChargingIcon,
  BatteryFullIcon,
  ComputerTowerIcon,
  NavigationArrowIcon,
  CircleIcon,
} from 'phosphor-react-native';

// Comprehensive icon mapping for database icon names
export const getIconFromDatabase = (iconName: string): React.ComponentType<any> => {
  const iconMap: { [key: string]: React.ComponentType<any> } = {
    // Basic shapes and symbols
    'circle': CircleIcon,
    'square': Square,
    'triangle': Triangle,
    'diamond': Diamond,
    'hexagon': Hexagon,
    'pentagon': Pentagon,
    'octagon': Octagon,
    'plus': Plus,
    'minus': Minus,
    'equals': Equals,
    'x': X,
    'check': Check,
    'warning': Warning,
    'info': Info,
    'question': Question,
    'exclamation': ExclamationMarkIcon,
    'exclamation-mark': ExclamationMarkIcon,
    
    // Navigation and location
    'map-pin': MapPin,
    'mappin': MapPin,
    'location': MapPin,
    'navigation': NavigationArrowIcon,
    'compass': Compass,
    'globe': Globe,
    'world': Globe,
    'flag': Flag,
    'country': Flag,
    
    // Buildings and structures
    'house': House,
    'home': House,
    'building': Building,
    'house-line': HouseLine,
    'houseline': HouseLine,
    'key': Key,
    'lock': Lock,
    'security': Lock,
    
    // Rooms and furniture
    'bed': Bed,
    'bedroom': Bed,
    'bathtub': Bathtub,
    'bathroom': Bathtub,
    'toilet': Toilet,
    'shower': Shower,
    'dress': Dress,
    'wardrobe': Dress,
    'closet': Dress,
    'backpack': Backpack,
    'storage': Backpack,
    'suitcase': Suitcase,
    'luggage': Suitcase,
    
    // Technology
    'wifi': WifiHigh,
    'wifi-high': WifiHigh,
    'internet': WifiHigh,
    'phone': Phone,
    'telephone': Phone,
    'computer': ComputerTowerIcon,
    'laptop': ComputerTowerIcon,
    'printer': Printer,
    'printing': Printer,
    'hard-drive': HardDrive,
    'harddrive': HardDrive,
    'camera': Camera,
    'photography': Camera,
    'video': Video,
    'video-camera': VideoCamera,
    'videocamera': VideoCamera,
    'video-camera-slash': VideoCameraSlash,
    'videocameraslash': VideoCameraSlash,
    'webcam': Webcam,
    'webcam-slash': WebcamSlash,
    'webcamslash': WebcamSlash,
    'monitor': Monitor,
    'screen': Monitor,
    'monitor-play': MonitorPlay,
    'monitorplay': MonitorPlay,
    'television': Television,
    'tv': Television,
    
    // Appliances and utilities
    'lightbulb': Lightbulb,
    'light': Lightbulb,
    'lighting': Lightbulb,
    'flashlight': Flashlight,
    'torch': Flashlight,
    'lamp': Lamp,
    'plug': Plug,
    'electricity': Plug,
    'power': Plug,
    'washing-machine': WashingMachine,
    'washingmachine': WashingMachine,
    'laundry': WashingMachine,
    'fan': Fan,
    'ventilation': Fan,
    'thermometer': Thermometer,
    'temperature': Thermometer,
    'thermometer-hot': ThermometerHot,
    'thermometerhot': ThermometerHot,
    'hot': ThermometerHot,
    'thermometer-cold': ThermometerCold,
    'thermometercold': ThermometerCold,
    'cold': ThermometerCold,
    
    // Transportation
    'car': Car,
    'parking': Car,
    'vehicle': Car,
    'airplane': Airplane,
    'airport': Airplane,
    'flight': Airplane,
    
    // Nature and weather
    'tree': Tree,
    'garden': Tree,
    'nature': Tree,
    'sun': Sun,
    'sunny': Sun,
    'balcony': Sun,
    'moon': Moon,
    'night': Moon,
    'cloud': Cloud,
    'cloudy': Cloud,
    'cloud-rain': CloudRain,
    'cloudrain': CloudRain,
    'rain': CloudRain,
    'cloud-snow': CloudSnow,
    'cloudsnow': CloudSnow,
    'snow': CloudSnow,
    'winter': CloudSnow,
    'cloud-lightning': CloudLightning,
    'cloudlightning': CloudLightning,
    'lightning': CloudLightning,
    'wind': Wind,
    'air': Wind,
    'fire': Fire,
    'heating': Fire,
    'snowflake': Snowflake,
    
    // Water and swimming
    'waves': Waves,
    'swimming-pool': SwimmingPool,
    'swimmingpool': SwimmingPool,
    'pool': SwimmingPool,
    'drop': Drop,
    'water': Drop,
    
    // Sports and fitness
    'barbell': Barbell,
    'gym': Barbell,
    'fitness': Barbell,
    'exercise': Barbell,
    
    // Entertainment
    'game-controller': GameController,
    'gamecontroller': GameController,
    'gaming': GameController,
    'music-note': MusicNote,
    'musicnote': MusicNote,
    'music': MusicNote,
    
    // Animals and pets
    'paw-print': PawPrint,
    'pawprint': PawPrint,
    'pets': PawPrint,
    'animals': PawPrint,
    
    // People and accessibility
    'baby': Baby,
    'child': Baby,
    'child-friendly': Baby,
    'childfriendly': Baby,
    'wheelchair': Wheelchair,
    'accessible': Wheelchair,
    'accessibility': Wheelchair,
    'users': Users,
    'guests': Users,
    'people': Users,
    'user': User,
    'person': User,
    'user-plus': UserPlus,
    'userplus': UserPlus,
    'add-user': UserPlus,
    'adduser': UserPlus,
    'user-minus': UserMinus,
    'userminus': UserMinus,
    'remove-user': UserMinus,
    'removeuser': UserMinus,
    'user-check': UserCheck,
    'usercheck': UserCheck,
    'verified-user': UserCheck,
    'verifieduser': UserCheck,
    
    // Security and safety
    'shield': Shield,
    'safety': Shield,
    'protection': Shield,
    
    // Food and drink
    'coffee': Coffee,
    'kitchen': Coffee,
    'cooking': Coffee,
    'food': Coffee,
    
    // Time and calendar
    'clock': Clock,
    'time': Clock,
    'calendar': Calendar,
    'schedule': Calendar,
    'date': Calendar,
    
    // Communication
    'bell': Bell,
    'notification': Bell,
    'alert': Bell,
    'bell-slash': BellSlash,
    'bellslash': BellSlash,
    'mute': BellSlash,
    'microphone': Microphone,
    'mic': Microphone,
    'microphone-slash': MicrophoneSlash,
    'microphoneslash': MicrophoneSlash,
    'mute-mic': MicrophoneSlash,
    'mutemic': MicrophoneSlash,
    'chat': Chat,
    'message': Chat,
    'chat-circle': ChatCircle,
    'chatcircle': ChatCircle,
    'chat-dots': ChatDots,
    'chatdots': ChatDots,
    'chat-text': ChatText,
    'chattext': ChatText,
    'chat-teardrop': ChatTeardrop,
    'chatteardrop': ChatTeardrop,
    'chat-teardrop-dots': ChatTeardropDots,
    'chatteardropdots': ChatTeardropDots,
    'chat-teardrop-text': ChatTeardropText,
    'chatteardroptext': ChatTeardropText,
    'phone-call': PhoneCall,
    'phonecall': PhoneCall,
    'call': PhoneCall,
    'phone-incoming': PhoneIncoming,
    'phoneincoming': PhoneIncoming,
    'phone-outgoing': PhoneOutgoing,
    'phoneoutgoing': PhoneOutgoing,
    'phone-slash': PhoneSlash,
    'phoneslash': PhoneSlash,
    'phone-x': PhoneX,
    'phonex': PhoneX,
    'envelope': Envelope,
    'email': Envelope,
    'mail': Envelope,
    'envelope-open': EnvelopeOpen,
    'envelopeopen': EnvelopeOpen,
    'mailbox': Mailbox,
    'paper-plane': PaperPlane,
    'paperplane': PaperPlane,
    'send': PaperPlane,
    
    // Files and documents
    'file': File,
    'document': File,
    'folder': Folder,
    'directory': Folder,
    'download': Download,
    'upload': Upload,
    'share': Share,
    'copy': Copy,
    'duplicate': Copy,
    'scissors': Scissors,
    'cut': Scissors,
    'trash': Trash,
    'delete': Trash,
    'archive': Archive,
    'bookmark': Bookmark,
    'bookmark-simple': BookmarkSimple,
    'bookmarksimple': BookmarkSimple,
    'tag': Tag,
    'label': Tag,
    'hash': Hash,
    'at': At,
    'link': Link,
    'url': Link,
    'link-break': LinkBreak,
    'linkbreak': LinkBreak,
    'paperclip': Paperclip,
    'attachment': Paperclip,
    
    // Presentation and charts
    'presentation': Presentation,
    'slide': Presentation,
    'presentation-chart': PresentationChart,
    'presentationchart': PresentationChart,
    'chart': PresentationChart,
    'trend-up': TrendUp,
    'trendup': TrendUp,
    'up': TrendUp,
    'increase': TrendUp,
    'trend-down': TrendDown,
    'trenddown': TrendDown,
    'down': TrendDown,
    'decrease': TrendDown,
    
    // Health and medical
    'pulse': Pulse,
    'heartbeat': Heartbeat,
    'health': Pulse,
    'medical': Pulse,
    
    // Science and education
    'planet': Planet,
    'space': Planet,
    'rocket': Rocket,
    'launch': Rocket,
    'telescope': Binoculars,
    'binoculars': Binoculars,
    'astronomy': Binoculars,
    'microscope': Microscope,
    'science': Microscope,
    'flask': Flask,
    'chemistry': Flask,
    'atom': Atom,
    'physics': Atom,
    'test-tube': TestTube,
    'testtube': TestTube,
    'experiment': TestTube,
    'graduation-cap': GraduationCap,
    'graduationcap': GraduationCap,
    'education': GraduationCap,
    'school': GraduationCap,
    'book': Book,
    'reading': Book,
    'book-open': BookOpen,
    'bookopen': BookOpen,
    'open-book': BookOpen,
    'openbook': BookOpen,
    'books': Books,
    'library': Books,
    'calculator': Calculator,
    'math': Calculator,
    'ruler': Ruler,
    'measure': Ruler,
    'measurement': Ruler,
    
    // Miscellaneous
    'star': Star,
    'rating': Star,
    'favorite': Star,
    'heart': Heart,
    'like': Heart,
    'love': Heart,
    'thumbs-up': ThumbsUp,
    'thumbsup': ThumbsUp,
    'approve': ThumbsUp,
    'eye': Eye,
    'view': Eye,
    'see': Eye,
    'eye-slash': EyeSlash,
    'eyeslash': EyeSlash,
    'hide': EyeSlash,
    'image': Image,
    'picture': Image,
    'photo': Image,
    'battery': BatteryChargingIcon,
    'elevator': Elevator,
    'lift': Elevator,
  };
  
  // Return the mapped icon or default to House if not found
  return iconMap[iconName.toLowerCase()] || House;
};

// Helper function to get icon component with size and color props
export const getIconComponent = (iconName: string, size: number = 20, color: string = '#222222') => {
  const IconComponent = getIconFromDatabase(iconName);
  return <IconComponent size={size} color={color} />;
};

// Helper function to check if an icon exists
export const hasIcon = (iconName: string): boolean => {
  const IconComponent = getIconFromDatabase(iconName);
  return IconComponent !== House || iconName.toLowerCase() === 'house';
};
